update to 1.9.13
liuyanxi975/Chinese-Translation-for-Vortex pull request #10
Opened 2024-02-15 03:42 UTC by Souma-Sumire

- 更新至 1.9.13
- 格式化以符合「盘古之白」排版规范
- 修改了一些文本

2024-02-15 05:34 UTC, SettingDust requested changes

2024-02-15 05:34 UTC, SettingDust commented on zh/collection.json
> +  "This screen lets you set up tweaks for the game ini file that will be applied to a user's setup when they use your collection.": "该分区允许你设置游戏 ini 文件的调整，当用户使用你的整合包时，这些调整将被应用到他们的设置中。",
collection 是否是“整合包”需要讨论，我偏向”收藏集“尊重原意或”模组集“易理解，不过都不太满意
这里是由某人特意制作的模组及配置集合，实际上和整合包的含义接近，但是有偏离
collection 隐含着是创建者的”收藏“的含义，也对应下文的 curator，不太好翻译

2024-02-15 05:34 UTC, SettingDust commented on zh/collections.json
> +  "This collection has {{count}} optional mods which are not required to complete the installation but have been recommended by the curator. To view these mods, click the button below.": "此整合包有 {{cou
策展人太奇怪了

2024-02-15 05:34 UTC, SettingDust commented on zh/collection.json
> +  "This screen lets you set up tweaks for the game ini file that will be applied to a user's setup when they use your collection.": "该分区允许你设置游戏 ini 文件的调整，当用户使用你的整合包时，这些调整将被应用到他们的设置中。",
screen 无分区含义，分区也和”这个画面“含义偏离

2024-02-15 06:44 UTC, Souma-Sumire commented on zh/collection.json
> +  "This screen lets you set up tweaks for the game ini file that will be applied to a user's setup when they use your collection.": "该分区允许你设置游戏 ini 文件的调整，当用户使用你的整合包时，这些调整将被应用到他们的设置中。",
3bdfd11 翻译为整合包，所以就顺用了。

2024-02-15 07:07 UTC, Souma-Sumire commented on zh/collection.json
> +  "This screen lets you set up tweaks for the game ini file that will be applied to a user's setup when they use your collection.": "该分区允许你设置游戏 ini 文件的调整，当用户使用你的整合包时，这些调整将被应用到他们的设置中。",
也可以叫 `合集` 、`作品集`  ？

都可以，我没什么意见。

2024-02-15 07:29 UTC, SettingDust commented on zh/collection.json
> +  "This screen lets you set up tweaks for the game ini file that will be applied to a user's setup when they use your collection.": "该分区允许你设置游戏 ini 文件的调整，当用户使用你的整合包时，这些调整将被应用到他们的设置中。",
合集感觉不错，@liuyanxi975 你的意见是？

2024-02-15 08:40 UTC, liuyanxi975 commented
感谢 pr，我会尽快查看～

2024-02-15 08:56 UTC, liuyanxi975 commented on zh/collection.json
> +  "This screen lets you set up tweaks for the game ini file that will be applied to a user's setup when they use your collection.": "该分区允许你设置游戏 ini 文件的调整，当用户使用你的整合包时，这些调整将被应用到他们的设置中。",
> 合集感觉不错，@liuyanxi975 你的意见是？

我之前采用“整合包”翻译的原因是顺应了中文论坛上的习惯性叫法。似乎大家一直以“整合包”来称呼一个由玩家自制的MOD合集。Vortex这个功能我没有具体用过，不清楚与论坛上的整合包有何差别。若功能上有很大差别，我赞成更名，以表区别。否则我仍建议使用“整合包”一词，因为我们没必要改变用户的原有语言习惯，使用已经广泛使用的词汇更方便用户理解。

2024-02-15 08:59 UTC, liuyanxi975 commented on zh/collections.json
> +  "This collection has {{count}} optional mods which are not required to complete the installation but have been recommended by the curator. To view these mods, click the button below.": "此整合包有 {{cou
建议直接翻译为”作者“即可。mod有作者，collection也有作者，这应该不会带来歧义。

2024-02-15 09:00 UTC, liuyanxi975 commented on zh/collection.json
> +  "This screen lets you set up tweaks for the game ini file that will be applied to a user's setup when they use your collection.": "该分区允许你设置游戏 ini 文件的调整，当用户使用你的整合包时，这些调整将被应用到他们的设置中。",
建议翻译为：“该界面”。

2024-02-15 10:30 UTC, liuyanxi975 requested changes

2024-02-15 10:30 UTC, liuyanxi975 commented on zh/common.json
> +  "Mod looks like a replacer": "模组看起来像是一个 Replacer",
建议将Replacer汉化处理，例如“补丁”？查询了一下，Replacer似乎是指明该mod是用来替换游戏中原有的某个角色或物品的，而区别于增加物品的mod。具体的翻译有待商榷

2024-02-15 10:30 UTC, liuyanxi975 commented on zh/common.json
> +  "When you select a language for the first time you may have to restart Vortex.": "第一次选择语言时，您可能需要重新启动 Vortex。　⁣⁣⁣⁣　⁣⁣⁣⁣本翻译贡献者：liuyanxi，xuqingxin，SettingDust，TUsama",
作者需要更新

2024-02-15 10:30 UTC, liuyanxi975 commented on zh/common.json
> +  "The curator of \"{{sourceName}}\" has provided additional instructions for installing \"{{title}}\". You can view these instructions now or check them later from the instructions column in the col
curator需要统一翻译

2024-02-15 10:30 UTC, liuyanxi975 commented on zh/common.json
> +  "The version of the game you have installed is different to the one the curator used when creating this collection.[br][/br][br][/br]Your game version: [style=dialog-success-text]{{actual}}[/style]
curator需要统一翻译

2024-02-15 10:30 UTC, liuyanxi975 commented on zh/common.json
> +  "Congratulations! Please consider endorsing this collection if you are enjoying it. Endorsing helps others discover this collection and lets the curator know you enjoyed it.": "恭喜！如果您喜欢这个整合包，请考虑为其点
curator需要统一翻译

2024-02-15 10:30 UTC, liuyanxi975 commented on zh/common.json
> +  " (Recommended by curator)": "（由策划者推荐）",
curator需要统一翻译

2024-02-15 10:30 UTC, liuyanxi975 commented on zh/collections.json
> +  "This collection has {{count}} optional mods which are not required to complete the installation but have been recommended by the curator. To view these mods, click the button below.": "此整合包有 {{cou
curator需要统一翻译

2024-02-15 13:14 UTC, SettingDust commented on zh/common.json
> +  "Mod looks like a replacer": "模组看起来像是一个 Replacer",
这里的 Replacer 是直接修改游戏原有文件并替换才能生效的模组，会和任一其他替换相同文件的 Replacer 冲突，是比较原始的模组模式

2024-02-15 13:15 UTC, SettingDust commented on zh/collection.json
> +  "This screen lets you set up tweaks for the game ini file that will be applied to a user's setup when they use your collection.": "该分区允许你设置游戏 ini 文件的调整，当用户使用你的整合包时，这些调整将被应用到他们的设置中。",
合集是这种作用的单词更常见的翻译，但是 NMM 这里实际上和 Pack 是混用的，因为包含了配置等非元数据内容
所以保留整合包也可

2024-02-15 14:12 UTC, liuyanxi975 commented on zh/common.json
> +  "Mod looks like a replacer": "模组看起来像是一个 Replacer",
> 这里的 Replacer 是直接修改游戏原有文件并替换才能生效的模组，会和任一其他替换相同文件的 Replacer 冲突，是比较原始的模组模式
> 
> 怎么翻译也没什么好的想法

那么，“替换”一词总是没错的，无论从单词含义还是实际用途。我想到了两个翻译：

这个模组看起来像是一个替换器
这看起来是一个替换类模组

2024-02-15 14:21 UTC, SettingDust commented on zh/common.json
> +  "Mod looks like a replacer": "模组看起来像是一个 Replacer",
“替换型”怎么样

2024-02-15 14:44 UTC, liuyanxi975 commented on zh/common.json
> +  "Mod looks like a replacer": "模组看起来像是一个 Replacer",
> “替换型”怎么样

Done

2024-02-15 14:48 UTC, liuyanxi975 commented
看起来似乎没问题了，试用两天后，若没问题，将会合并。再次感谢您的PR以及 @SettingDust 的协助~

2024-02-16 01:34 UTC, SettingDust commented
中文与全角标点符号间不该有空格

2024-02-16 01:46 UTC, Souma-Sumire commented
> 中文与全角标点符号间不该有空格

你说的对

2024-02-19 06:48 UTC, merged