更新
liuyanxi975/Chinese-Translation-for-Vortex pull request #8
Opened 2021-01-20 11:41 UTC by SettingDust

- 更新1.3.22

- 使用工具重新导出 Vortex 语言文件键，配合自编小程序混合原有翻译至新文件，消除大量冗余语言键，可能造成部分键丢失，无法测试完全，目前本地测试完全通过。

- 修复部分汉化不完全，Vortex 本身漏洞导致部分（似乎是除 common.json 之外都有问题）语言文件无法正常读取，添加部分可测试键到common.json后汉化正常显示

2021-02-02 12:17 UTC, SettingDust commented
需要测试，我的游戏只有一个

2021-02-15 07:08 UTC, SettingDust commented
即将更新1.4，等待更新后再继续修正翻译

2021-06-29 04:20 UTC, TUsama requested changes
一部分。主要问题是标点符号和mod翻译成模组的问题。修改起来倒也不是很困难。句意有问题的我都标注出来了，句式修改的可以采纳也可不采纳。

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "The quick brown fox jumps over the lazy dog": "敏捷的棕色狐狸跨过懒狗",
我不太确定这里是否可以直译，尤其是考虑到这个句子本身的意思与句子作用完全无关。

或可参考：https://www.zhihu.com/question/20533417

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "buttons on": "按钮在",
似与 1552 行相同。不清楚在vortex中冗余键值是否可能会引起问题。

并且考虑到句子中的元素不似 mc 那样可以移动，或许可以改成如下形式：
对 [按钮] 进行处理，按钮位于 [地址]。
或者也可以和官方沟通？这个句子框架基本不可能有好的解决方案。我这个如果你觉得也不行的话，弃用也无妨。

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "Chrome requires a change to a configuration file to allow an external program to handle links where chrome doesn't know the protocol. As of chrome 77 this also allows This is the case for the \"Do
```suggestion
  "Chrome requires a change to a configuration file to allow an external program to handle links where chrome doesn't know the protocol. As of chrome 77 this also allows This is the case for the \"Download with Manager\" buttons on Nexus.\n\nWe can apply this change for you, but only if all instances of Chrome are closed, otherwise it will look like it worked but the change is reset when chrome closes.\n\nTo clarify: we're only enabling support for nxm:// links as used on nexusmods, we're not changing anything else.\n": "Chrome需要修改配置文件，以允许外部程序处理Chrome未知的协议链接。在chrome 77中，Nexus上的 \"Download with Manager\" 按钮就是运用这一点实现的。\n\n我们可以为您修改配置文件，但在此之前，您必须关闭所有的Chrome窗口/进程，否则当您下一次启动Chrome时，配置文件会被还原，导致修改失效。\n\n声明：我们对于Chrome配置文件的修改仅用于支持nxm://协议，这样您就能通过nexusmods直接使用Vortex，除此之外我们不会更改任何其他内容。\n",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "You can choose to either receive automatic updates only after they went through some community testing (Stable) or to always get the newest features (Beta).": "您可以选择自动更新是否在需要社区测试后（稳定版）或总是尝试最新的特性（B
```suggestion
  "You can choose to either receive automatic updates only after they went through some community testing (Stable) or to always get the newest features (Beta).": "您可以选择仅在需要社区测试（稳定版）时进行自动更新，或总是自动更新，尝鲜最新特性（Beta版）。",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "When you install a mod through Vortex it is stored in a separate directory and has no immediate effect on the game. We call the process of actually placing the files into the game directory \"depl
有“mod”残留。

```suggestion
  "When you install a mod through Vortex it is stored in a separate directory and has no immediate effect on the game. We call the process of actually placing the files into the game directory \"deployment\".\n\nThere are different methods available in Vortex to do this Deployment, the best one will usually get picked automatically, based on which game you're modding and your system configuration.\nAll methods have in common that deployment is way quicker than copying files and consumes no or very little additional disk space.\n\nBy default, deployment happens automatically after you enable/disable a mod.\nIf you want more control you can disable this automation and will then have to manually click a button to start the deployment.\n\nPlease note that parts of Vortex (i.e. the list of plugins for TES games) will only reflect the \"deployed\" state.": "当你通过Vortex安装Mod时，它会存储在独立目录中，并且不会立刻影响游戏。我们将实际将文件放入游戏目录的过程称为\"部署\"。\n\nVortex中有多种可用方式进行部署，通常会根据您修改的游戏及系统设置自动选择最佳方法。\n所有方法的共同点是，部署比复制文件要快得多，并且不占用或几乎不占用额外的硬盘空间。\n\n默认情况下，启用/禁用mod后会自动进行部署。\n如果需要更多控制，您可以禁用此自动功能，然后必须手动点击按钮才能开始部署。\n\n请注意，Vortex的某些部分（即TES游戏的插件列表）将体现为\"已部署\"状态。",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "When you select a language for the first time you may have to restart Vortex.": "第一次选择语言时，可能需要重新启动Vortex。",
```suggestion
  "When you select a language for the first time you may have to restart Vortex.": "第一次选择语言时，你可能需要重新启动Vortex。",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "Makes all system fonts installed on the system available in the Font dropdowns. This function seems to cause Vortex to crash for a very small number of users and we have not been able to identify
```suggestion
  "Makes all system fonts installed on the system available in the Font dropdowns. This function seems to cause Vortex to crash for a very small number of users and we have not been able to identify what sets the affected systems apart yet.": "使所有系统已安装字体在“字体”下拉列表中可用，这个功能会导致极少数用户的Vortex崩溃，并且我们还无法确认是什么因素导致系统受影响。",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "Please understand that this is only for feedback for the \"Vortex\" application, all feedback regarding the website \"Nexus Mods\" will be ignored.": "请明白这仅用于\"Vortex\"应用程序的反馈，有关网站\"Nexus Mods\"的所
```suggestion
  "Please understand that this is only for feedback for the \"Vortex\" application, all feedback regarding the website \"Nexus Mods\" will be ignored.": "请注意，这仅用于\"Vortex\"应用程序的反馈，有关网站\"Nexus Mods\"的所有反馈将被忽略。",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "feedback-instructions": "请注意以下几点,<1></1><2><0>请使用标点符号以及换行</0><1>请使用英语</1><2>请尽可能简洁精准的描述问题。您甚至不用写成一个完整的句子。因为漏洞反馈是一个技术性文档，不是散文</2><3>一个反馈只能描述一个问题</3><4>请不要进行盲目猜测或立即下您自己的结论。只需要描述您现在看到的以及您希望看到的</4><5>
```suggestion
  "feedback-instructions": "请注意以下几点：<1></1><2><0>请使用标点符号以及换行</0><1>请使用英语</1><2>请尽可能简洁精准地描述问题。您甚至不用将问题描述写成一个完整的句子。因为漏洞反馈是一个技术性文档，不是散文</2><3>一个反馈只能描述一个问题</3><4>请不要进行盲目猜测或立即下您自己的结论。只需要描述您现在看到的以及您希望看到的</4><5>下面提供了一个关于如何报告Bug的范例，请参考</5></2>修复Bug是个极其耗费时间的工作。如果您能将反馈写的尽可能好，我们就能花更少的时间在这上面，从而拥有更多的精力完善Vortex！",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "Managed ({{filterCount}})": "管理： ({{filterCount}})",
```suggestion
  "Managed ({{filterCount}})": "已管理： ({{filterCount}})",
```
我不太确定中文标点后面的空格是否需要或者可以删去。

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "Scan:": "扫描:",
```suggestion
  "Scan:": "扫描：",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "feedback-instructions-question": "<0>抱歉，这不是向Vortex寻求帮助的正确方法。 反馈系统旨在告知我们关于Vortex的问题以及可能进行的改进，我们在回复时仅是向您了解更多详细信息，而非解决您的疑惑。要获得帮助，请查询知识库或访问论坛</0><1>https://forums.nexusmods.com/index.php?/forum/4306-v
```suggestion
  "feedback-instructions-question": "<0>抱歉，这不是向Vortex寻求帮助的正确方法。反馈系统旨在告知我们关于Vortex的问题以及可能进行的改进，我们在回复时仅是向您了解更多详细信息，而非解决您的疑惑。要获得帮助，请查询知识库或访问论坛</0><1>https://forums.nexusmods.com/index.php?/forum/4306-vortex-support/</1><2>这样整个社区都可以帮助您。</2>",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "Your game may not be supported yet but adding it yourself may be easier than you think. Click to learn how!": "您的游戏可能还不受支持，但您自己添加它可能比您想象的要容易。点击了解方法！",
```suggestion
  "Your game may not be supported yet but adding it yourself may be easier than you think. Click to learn how!": "您的游戏可能还不受支持，但自行添加它并不如您想象中的那么困难。点击了解方法！",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "{{ count }} download_plural": "{{ count }} 个下载",
想确认一下，为什么有些数字与中文之间有空格，有些没有？

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "E.g.:\nSummary: The mod downloads properly but when I try to install it nothing happens.\nExpected Results: The mod is installed.\nActual Results: Nothing happens.\nSteps to reproduce: Download a
```suggestion
  "E.g.:\nSummary: The mod downloads properly but when I try to install it nothing happens.\nExpected Results: The mod is installed.\nActual Results: Nothing happens.\nSteps to reproduce: Download a mod, then click Install inside the Actions menu.": "范例：\nSummary: The mod downloads properly but when I try to install it nothing happens.\nExpected Results: The mod is installed.\nActual Results: Nothing happens.\nSteps to reproduce: Download a mod, then click Install inside the Actions menu.",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "You have configured Vortex to run FNIS automatically but it's not installed for this game. For the automation to work, FNIS has to be installed and configured for the current game. You can downloa
```suggestion
  "You have configured Vortex to run FNIS automatically but it's not installed for this game. For the automation to work, FNIS has to be installed and configured for the current game. You can download it from [url]{{url}}[/url].": "您已将Vortex配置为自动运行FNIS，但你并没有安装它。若想让它自动运行，您必须为当前游戏安装和配置FNIS。您可以从[url]{{url}}[/url]下载它。",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "You have configured Vortex to run FNIS automatically but the installed version of FNIS is too old and doesn't support being embedded. Please download and install at least version 7.4 from [url]{{u
```suggestion
  "You have configured Vortex to run FNIS automatically but the installed version of FNIS is too old and doesn't support being embedded. Please download and install at least version 7.4 from [url]{{url}}[/url].": "您已经将Vortex配置为自动运行FNIS，但已安装的FNIS版本太旧，不支持嵌入。请从[url]{{url}}[/url]下载并安装，版本最低要求为7.4。",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
>    "An unknown error occurred starting FNIS. This is usually caused by a broken installation or the tool being set up incorrectly.": "启动FNIS时发生未知错误。这通常是由于安装失败或工具设置不正确造成的。",
```suggestion
  "An unknown error occurred starting FNIS. This is usually caused by a broken installation or the tool being set up incorrectly.": "启动FNIS时发生未知错误。这通常是由于安装失败或工具设置不正确。",
```
句式杂糅。

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "Please select the patches to activate in FNIS (when run automatically!).\nOnly select patches you have the corresponding mod for!\nThis list is stored separately for each profile.": "请选择FNIS中激活的补丁
似乎第一句句意有些差错，但由于我并不知道这个东西的工作原理，所以我就不 suggest 了。

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "Pillars of Eternity 2 wasn't discovered": "Pillars of Eternity 2 未被发现",
```suggestion
  "Pillars of Eternity 2 wasn't discovered": "未找到 Pillars of Eternity 2",
```

2021-06-29 04:20 UTC, TUsama commented on zh/common.json
> +  "This adds a mod to vortex that provides Archive Invalidation similar to mods like \"Archive Invalidation Invalidated\".": "This adds a mod to vortex that provides Archive Invalidation similar to m
漏译？

2021-06-29 11:14 UTC, TUsama commented on zh/common.json
> +  "Previous": "以前",
```suggestion
  "Previous": "以前",
```

2021-06-29 13:30 UTC, SettingDust commented on zh/common.json
> +  "Previous": "以前",
上一个会比较好 ？和下一个统一，或者俩都改？

2022-01-26 06:14 UTC, merged

2022-01-26 08:35 UTC, liuyanxi975 commented
已合并。但发现大量文本翻译缺失。目前准备采用已修改的新翻译的同时，合并来自过去的完整翻译，补充缺漏。同时再合并来自最新Vortex源码的未翻译文本，翻译还在进行中。
ps: 从源码提取翻译，并合并旧翻译，有人做了工具，我一直在使用。地址：https://www.nexusmods.com/site/mods/33

2022-01-26 09:07 UTC, liuyanxi975 commented on zh/common.json
> +  "{{ count }} download_plural": "{{ count }} 个下载",
因为这是纯手动敲的。。总会有遗漏。我本意是想加上空格，看起来可能舒服点。当然我也没太在意这个细节。包括句子中各种空格问题，有些时候是逐句翻译，但是英文的标点后有空格，在翻译时就忘记去除。包括冒号的问题，因为疏忽部分英文冒号也没有换成中文冒号。。可能我是一个不太注意细节的人哈哈

2022-01-26 09:14 UTC, liuyanxi975 commented on zh/common.json
> +  "Previous": "以前",
您好，您的翻译我已经在我的本地合并完毕，将随下个版本一并更新。我会在翻译文件内为您署名，感谢